site_name: Development Setup Handbook
site_url: https://learn-with-me.github.io/Development-Setup-Handbook/
repo_url: https://github.com/learn-with-me/Development-Setup-Handbook
docs_dir: 'src'

# nav:
#     ## add your custom pages hierarchy here
#     - Page 1: index.md
#     - Page 2: index.md
#     - Page 3: index.md
#     - Page 4: index.md
#     - About: about.md

theme:
  name: material
  logo: assets/images/logo.png
#   favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.indexes
    - navigation.top
    # - toc.integrate
  plugins:
    - tags
extra:
  homepage: https://learn-with-me.github.io/Development-Setup-Handbook/
  copyright: Copyright &copy; 2022 - 2023 goel4ever
  analytics:
    provider: google
    property: G-DDM7Y35EZW
